sh_test(
    name = "integration_test",
    srcs = ["integration_test.sh"],
    data = [
        "//client:hermes_client",
        "//server/ch/execve/hermes:hermes_server",
        "//tests/config",
        "//tests/data",
    ],
)